apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress-tls-cert.yaml

patches:
- path: patches/deployment.yaml
- target:
    kind: Ingress
    name: opencost-ingress
    namespace: opencost
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: opencost.hub-test-02.hub.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: opencost.hub-test-02.hub.com
- target:
    kind: Ingress
    name: opencost-report-ingress
    namespace: opencost
  patch: |
    - op: replace
      path: /spec/rules/0/host
      value: opencost-report.hub-test-02.hub.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: opencost-report.hub-test-02.hub.com
